spring:
  application:
    name: location_service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:location
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10